package com.finalwork.qunawan.dao;

import com.finalwork.qunawan.pojo.Comment;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Component(value = "commentMapper")
public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    Comment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    List<Comment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int updateByPrimaryKey(Comment record);

    int selectCountByTripId(int tripid);
    List<Comment> selectByTripId(int tripid);
    Integer selectUsefullCountByid(@Param("isusefull") String  isusefull, @Param("id") Integer  id);

    void updateIsUsefull(@Param("isusefull") String  isusefull, @Param("num") Integer  num,@Param("id") Integer  id);
    int selectCountByUserId(int userid);

}