package com.finalwork.qunawan.dao;

import com.finalwork.qunawan.pojo.Contact;
import org.springframework.stereotype.Component;

import java.util.List;
@Component(value = "contactMapper")
public interface ContactMapper {
    List<Contact> selectByUser(int uid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int insert(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    Contact selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    List<Contact> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int updateByPrimaryKey(Contact record);
}