package com.finalwork.qunawan.dao;

import com.finalwork.qunawan.pojo.Dates;
import org.springframework.stereotype.Component;

import java.util.List;

@Component(value = "datesMapper")
public interface DatesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dates
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dates
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int insert(Dates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dates
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    Dates selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dates
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    List<Dates> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dates
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int updateByPrimaryKey(Dates record);

    List<Dates> selectByTripId(int tripid);
}