package com.finalwork.qunawan.dao;

import com.finalwork.qunawan.pojo.Detail;
import org.springframework.stereotype.Component;

import java.util.List;

@Component(value = "detailMapper")
public interface DetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int insert(Detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    Detail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    List<Detail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int updateByPrimaryKey(Detail record);

    Detail selectByTripId(int tripid);
}