package com.finalwork.qunawan.dao;

import com.finalwork.qunawan.globle.Constants;
import com.finalwork.qunawan.pojo.Ordercontact;
import org.apache.ibatis.annotations.Param;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import java.util.List;

@Component(value = "ordercontactMapper")
public interface OrdercontactMapper {
    List<Ordercontact> getOrderContacts(@Param("orderId") int orderId,@Param("type") int type);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordercontact
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordercontact
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int insert(Ordercontact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordercontact
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    Ordercontact selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordercontact
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    List<Ordercontact> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordercontact
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int updateByPrimaryKey(Ordercontact record);
}