package com.finalwork.qunawan.dao;

import com.finalwork.qunawan.pojo.Price;
import org.springframework.stereotype.Component;

import java.util.List;
@Component(value = "priceMapper")
public interface PriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int insert(Price record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    Price selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    List<Price> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int updateByPrimaryKey(Price record);

    List<Price> selectPriceByTripId(int trip);
}