package com.finalwork.qunawan.dao;

import com.finalwork.qunawan.pojo.Sequence;
import org.springframework.stereotype.Component;

import java.util.List;
@Component(value="sequenceMapper")
public interface SequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated Tue Jun 18 12:28:25 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated Tue Jun 18 12:28:25 CST 2019
     */
    int insert(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated Tue Jun 18 12:28:25 CST 2019
     */
    Sequence selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated Tue Jun 18 12:28:25 CST 2019
     */
    List<Sequence> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated Tue Jun 18 12:28:25 CST 2019
     */
    int updateByPrimaryKey(Sequence record);

    Sequence selectByValue(String value);
    Sequence selectByKeyAndType(String key,String type);
}