package com.finalwork.qunawan.dao;

import com.finalwork.qunawan.pojo.Theme;
import org.springframework.stereotype.Component;

import java.util.List;
@Component(value = "themeMapper")
public interface ThemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Tue Jun 18 11:34:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Tue Jun 18 11:34:45 CST 2019
     */
    int insert(Theme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Tue Jun 18 11:34:45 CST 2019
     */
    Theme selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Tue Jun 18 11:34:45 CST 2019
     */
    List<Theme> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Tue Jun 18 11:34:45 CST 2019
     */
    int updateByPrimaryKey(Theme record);
    List<Theme> selectByType(int type);
    List<Theme> selectByName(String name);

}