package com.finalwork.qunawan.dao;

import com.finalwork.qunawan.pojo.Themeontrip;
import org.springframework.stereotype.Component;

import java.util.List;
@Component(value = "themeontripMapper")
public interface ThemeontripMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table themeontrip
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table themeontrip
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int insert(Themeontrip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table themeontrip
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    Themeontrip selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table themeontrip
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    List<Themeontrip> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table themeontrip
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int updateByPrimaryKey(Themeontrip record);
    List<Themeontrip>  selectByTripId(int tripid);
}