package com.finalwork.qunawan.dao;

import com.finalwork.qunawan.pojo.Traffic;
import java.util.List;

public interface TrafficMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int insert(Traffic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    Traffic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    List<Traffic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    int updateByPrimaryKey(Traffic record);
}