package com.finalwork.qunawan.pojo;

public class Detail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.id
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.trip
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    private Integer trip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.place
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    private String place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.hotel
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    private String hotel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.food
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    private String food;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.id
     *
     * @return the value of detail.id
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.id
     *
     * @param id the value for detail.id
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.trip
     *
     * @return the value of detail.trip
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public Integer getTrip() {
        return trip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.trip
     *
     * @param trip the value for detail.trip
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public void setTrip(Integer trip) {
        this.trip = trip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.place
     *
     * @return the value of detail.place
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.place
     *
     * @param place the value for detail.place
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.hotel
     *
     * @return the value of detail.hotel
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public String getHotel() {
        return hotel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.hotel
     *
     * @param hotel the value for detail.hotel
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public void setHotel(String hotel) {
        this.hotel = hotel == null ? null : hotel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.food
     *
     * @return the value of detail.food
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public String getFood() {
        return food;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.food
     *
     * @param food the value for detail.food
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public void setFood(String food) {
        this.food = food == null ? null : food.trim();
    }
}