package com.finalwork.qunawan.pojo;

public class Ordercontact {
    public Contact getContactObject() {
        return contactObject;
    }

    public void setContactObject(Contact contactObject) {
        this.contactObject = contactObject;
    }

    public Orders getOrder() {
        return order;
    }

    public void setOrder(Orders order) {
        this.order = order;
    }
    /**
     * 订单对象
     */
    private Orders order;

    private Contact contactObject;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordercontact.id
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    private Integer id;

    /**
     * 订单编号
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordercontact.orders
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    private Integer orders;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordercontact.contact
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    private Integer contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordercontact.type
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordercontact.id
     *
     * @return the value of ordercontact.id
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordercontact.id
     *
     * @param id the value for ordercontact.id
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordercontact.orders
     *
     * @return the value of ordercontact.orders
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public Integer getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordercontact.orders
     *
     * @param orders the value for ordercontact.orders
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public void setOrders(Integer orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordercontact.contact
     *
     * @return the value of ordercontact.contact
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public Integer getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordercontact.contact
     *
     * @param contact the value for ordercontact.contact
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public void setContact(Integer contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordercontact.type
     *
     * @return the value of ordercontact.type
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordercontact.type
     *
     * @param type the value for ordercontact.type
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }
}