package com.finalwork.qunawan.pojo;

import java.util.List;

public class Schedule {

    private Traffic trafficObject;
    private List<Dates> dates;

    public List<Dates> getDates() {
        return dates;
    }

    public void setDates(List<Dates> dates) {
        this.dates = dates;
    }

    public Traffic getTrafficObject() {
        return trafficObject;
    }

    public void setTrafficObject(Traffic trafficObject) {
        this.trafficObject = trafficObject;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.id
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.trip
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    private Integer trip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.traffic
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    private Integer traffic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.id
     *
     * @return the value of schedule.id
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.id
     *
     * @param id the value for schedule.id
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.trip
     *
     * @return the value of schedule.trip
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public Integer getTrip() {
        return trip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.trip
     *
     * @param trip the value for schedule.trip
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public void setTrip(Integer trip) {
        this.trip = trip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.traffic
     *
     * @return the value of schedule.traffic
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public Integer getTraffic() {
        return traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.traffic
     *
     * @param traffic the value for schedule.traffic
     *
     * @mbg.generated Tue Jun 18 13:55:50 CST 2019
     */
    public void setTraffic(Integer traffic) {
        this.traffic = traffic;
    }
}