package com.finalwork.qunawan.pojo;

public class Theme {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theme.id
     *
     * @mbg.generated Tue Jun 18 11:34:45 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theme.name
     *
     * @mbg.generated Tue Jun 18 11:34:45 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theme.id
     *
     * @return the value of theme.id
     *
     * @mbg.generated Tue Jun 18 11:34:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theme.id
     *
     * @param id the value for theme.id
     *
     * @mbg.generated Tue Jun 18 11:34:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theme.name
     *
     * @return the value of theme.name
     *
     * @mbg.generated Tue Jun 18 11:34:45 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theme.name
     *
     * @param name the value for theme.name
     *
     * @mbg.generated Tue Jun 18 11:34:45 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}